--------------------------------------------------------
--  파일이 생성됨 - 월요일-6월-01-2020   
--------------------------------------------------------
DROP TABLE "ACTION_FILES" cascade constraints;
DROP TABLE "APPROVAL" cascade constraints;
DROP TABLE "APPROVALDOC" cascade constraints;
DROP TABLE "APPROVALFILE" cascade constraints;
DROP TABLE "APPROVALFORM" cascade constraints;
DROP TABLE "APPROVALPATH" cascade constraints;
DROP TABLE "APPROVALREFERRER" cascade constraints;
DROP TABLE "CHATROOMS" cascade constraints;
DROP TABLE "DUTYS" cascade constraints;
DROP TABLE "EVENTS" cascade constraints;
DROP TABLE "EVENT_GROUPS" cascade constraints;
DROP TABLE "EVENT_TYPES" cascade constraints;
DROP TABLE "MESSAGES" cascade constraints;
DROP TABLE "NOTES" cascade constraints;
DROP TABLE "PARTICIPATIONS" cascade constraints;
DROP TABLE "POSITIONS" cascade constraints;
DROP TABLE "PROJECTS" cascade constraints;
DROP TABLE "PROJECT_ISSUES" cascade constraints;
DROP TABLE "PROJECT_ISSUE_TYPES" cascade constraints;
DROP TABLE "PROJECT_MEMBERS" cascade constraints;
DROP TABLE "PROJECT_OUTPUTS" cascade constraints;
DROP TABLE "PROJECT_OUTPUT_TYPES" cascade constraints;
DROP TABLE "PROJECT_STATUS" cascade constraints;
DROP TABLE "PROJECT_TASKS" cascade constraints;
DROP TABLE "PROJECT_TASK_GROUPS" cascade constraints;
DROP TABLE "PROJECT_TASK_MANAGERS" cascade constraints;
DROP TABLE "PROJECT_TASK_STATUS" cascade constraints;
DROP TABLE "PROJECT_TYPES" cascade constraints;
DROP TABLE "TEAMS" cascade constraints;
DROP TABLE "USERS" cascade constraints;
--------------------------------------------------------
--  DDL for Table ACTION_FILES
--------------------------------------------------------

  CREATE TABLE "ACTION_FILES" 
   (	"ACTIONFILE_CODE" VARCHAR2(30 BYTE), 
	"ACTIONFILE_NAME" VARCHAR2(100 BYTE), 
	"ACTIONFILE_PATH" VARCHAR2(200 BYTE), 
	"ISSUE_CODE" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table APPROVAL
--------------------------------------------------------

  CREATE TABLE "APPROVAL" 
   (	"AP_NO" NUMBER, 
	"AP_DOC_NO" NUMBER, 
	"AP_APPROVER" VARCHAR2(50 BYTE), 
	"AP_DUTY_NAME" VARCHAR2(30 BYTE), 
	"AP_STEP" NUMBER, 
	"AP_RESULT" CHAR(1 BYTE), 
	"AP_COMMENT" VARCHAR2(3000 BYTE), 
	"AP_RECEIVEDATE" DATE, 
	"AP_SIGNDATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table APPROVALDOC
--------------------------------------------------------

  CREATE TABLE "APPROVALDOC" 
   (	"AP_DOC_NO" NUMBER, 
	"AP_FORM_NO" NUMBER, 
	"AP_DOC_WRITER" VARCHAR2(50 BYTE), 
	"AP_DOC_TITLE" VARCHAR2(1000 BYTE), 
	"AP_DOC_CONTENT" CLOB, 
	"AP_DOC_STATUS" CHAR(1 BYTE), 
	"AP_DOC_STEP" NUMBER, 
	"AP_DOC_CREATEDATE" DATE, 
	"AP_DOC_ENDDATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("AP_DOC_CONTENT") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
--------------------------------------------------------
--  DDL for Table APPROVALFILE
--------------------------------------------------------

  CREATE TABLE "APPROVALFILE" 
   (	"AP_FILE_NO" NUMBER, 
	"AP_DOC_NO" NUMBER, 
	"AP_FILE_NAME" VARCHAR2(500 BYTE), 
	"AP_FILE_PATH" VARCHAR2(500 BYTE), 
	"AP_FILE_TYPE" CHAR(1 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table APPROVALFORM
--------------------------------------------------------

  CREATE TABLE "APPROVALFORM" 
   (	"AP_FORM_NO" NUMBER, 
	"AP_PATH_NO" NUMBER, 
	"AP_FORM_NAME" VARCHAR2(200 BYTE), 
	"AP_FORM_CONTENT" CLOB
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("AP_FORM_CONTENT") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
--------------------------------------------------------
--  DDL for Table APPROVALPATH
--------------------------------------------------------

  CREATE TABLE "APPROVALPATH" 
   (	"AP_PATH_NO" NUMBER, 
	"AP_PATH1" VARCHAR2(20 BYTE), 
	"AP_PATH2" VARCHAR2(20 BYTE), 
	"AP_PATH3" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table APPROVALREFERRER
--------------------------------------------------------

  CREATE TABLE "APPROVALREFERRER" 
   (	"AP_DOC_NO" NUMBER, 
	"AP_REFERRER" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CHATROOMS
--------------------------------------------------------

  CREATE TABLE "CHATROOMS" 
   (	"CONVERSATION_ID" VARCHAR2(50 BYTE), 
	"LAST_MESSAGE_ID" NUMBER, 
	"CONVERSATION_CREATION_TIME" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DUTYS
--------------------------------------------------------

  CREATE TABLE "DUTYS" 
   (	"DUTY_CODE" VARCHAR2(30 BYTE), 
	"DUTY_NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EVENTS
--------------------------------------------------------

  CREATE TABLE "EVENTS" 
   (	"EVENT_ID" VARCHAR2(50 BYTE), 
	"EVENT_TITLE" VARCHAR2(100 BYTE), 
	"EVENT_START_DATE" DATE, 
	"EVENT_FINISH_DATE" DATE, 
	"EVENT_DESCRIPTION" VARCHAR2(500 BYTE), 
	"EVENT_ALL_DAY" CHAR(1 BYTE), 
	"EVENT_PLACE" VARCHAR2(50 BYTE), 
	"EVENT_TYPE_ID" VARCHAR2(30 BYTE), 
	"PROJECT_CODE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EVENT_GROUPS
--------------------------------------------------------

  CREATE TABLE "EVENT_GROUPS" 
   (	"EVENT_ID" VARCHAR2(50 BYTE), 
	"USER_ID" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EVENT_TYPES
--------------------------------------------------------

  CREATE TABLE "EVENT_TYPES" 
   (	"EVENT_TYPE_ID" VARCHAR2(30 BYTE), 
	"EVENT_TYPE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MESSAGES
--------------------------------------------------------

  CREATE TABLE "MESSAGES" 
   (	"MESSAGE_ID" NUMBER, 
	"AUTHOR_ID" VARCHAR2(50 BYTE), 
	"CONVERSATION_ID" VARCHAR2(50 BYTE), 
	"CONTENT" VARCHAR2(1000 BYTE), 
	"CREATION_TIME" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table NOTES
--------------------------------------------------------

  CREATE TABLE "NOTES" 
   (	"NOTE_ID" NUMBER, 
	"AUTHOR_ID" VARCHAR2(50 BYTE), 
	"RECEIVER_ID" VARCHAR2(50 BYTE), 
	"CONTENT" VARCHAR2(1000 BYTE), 
	"CREATION_TIME" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PARTICIPATIONS
--------------------------------------------------------

  CREATE TABLE "PARTICIPATIONS" 
   (	"USER_ID" VARCHAR2(50 BYTE), 
	"CONVERSATION_ID" VARCHAR2(50 BYTE), 
	"JOIN_TIME" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table POSITIONS
--------------------------------------------------------

  CREATE TABLE "POSITIONS" 
   (	"POSITION_CODE" NUMBER, 
	"POSITION_NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROJECTS
--------------------------------------------------------

  CREATE TABLE "PROJECTS" 
   (	"PROJECT_CODE" VARCHAR2(50 BYTE), 
	"PROJECT_NAME" VARCHAR2(100 BYTE), 
	"PROJECT_SUBNAME" VARCHAR2(10 BYTE), 
	"PROJECT_START" DATE, 
	"PROJECT_FINISH" DATE, 
	"PROJECT_PM" VARCHAR2(50 BYTE), 
	"PROJECT_TYPECODE" VARCHAR2(30 BYTE), 
	"PROJECT_PMO" VARCHAR2(50 BYTE), 
	"PROJECT_DESCRIPTION" VARCHAR2(500 BYTE), 
	"PROJECT_PRIORITY" NUMBER, 
	"PROJECT_STATUSCODE" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROJECT_ISSUES
--------------------------------------------------------

  CREATE TABLE "PROJECT_ISSUES" 
   (	"ISSUE_CODE" VARCHAR2(30 BYTE), 
	"ISSUE_NAME" VARCHAR2(100 BYTE), 
	"ISSUE_DESCRIPTION" VARCHAR2(500 BYTE), 
	"ISSUE_USER_ID" VARCHAR2(50 BYTE), 
	"ISSUE_DATE" DATE, 
	"ISSUE_ACTION_ID" VARCHAR2(50 BYTE), 
	"ISSUE_ACTION_DATE" DATE, 
	"ISSUE_TYPE_CODE" VARCHAR2(30 BYTE), 
	"TASK_CODE" VARCHAR2(30 BYTE), 
	"ISSUE_FILE_NAME" VARCHAR2(200 BYTE), 
	"ISSUE_FILE_PATH" VARCHAR2(300 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROJECT_ISSUE_TYPES
--------------------------------------------------------

  CREATE TABLE "PROJECT_ISSUE_TYPES" 
   (	"ISSUE_TYPE_CODE" VARCHAR2(30 BYTE), 
	"ISSUE_TYPE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROJECT_MEMBERS
--------------------------------------------------------

  CREATE TABLE "PROJECT_MEMBERS" 
   (	"PROJECT_JOINCODE" VARCHAR2(30 BYTE), 
	"PROJECT_CODE" VARCHAR2(50 BYTE), 
	"USER_ID" VARCHAR2(50 BYTE), 
	"DUTY_CODE" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROJECT_OUTPUTS
--------------------------------------------------------

  CREATE TABLE "PROJECT_OUTPUTS" 
   (	"OUTPUT_CODE" VARCHAR2(30 BYTE), 
	"OUTPUT_NAME" VARCHAR2(100 BYTE), 
	"OUTPUT_USER" VARCHAR2(50 BYTE), 
	"OUTPUT_DATE" DATE, 
	"OUTPUT_PATH" VARCHAR2(100 BYTE), 
	"OUTPUT_TYPE_CODE" VARCHAR2(30 BYTE), 
	"TASK_CODE" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROJECT_OUTPUT_TYPES
--------------------------------------------------------

  CREATE TABLE "PROJECT_OUTPUT_TYPES" 
   (	"OUTPUT_TYPE_CODE" VARCHAR2(30 BYTE), 
	"OUTPUT_TYPE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROJECT_STATUS
--------------------------------------------------------

  CREATE TABLE "PROJECT_STATUS" 
   (	"PROJECT_STATUSCODE" VARCHAR2(30 BYTE), 
	"PROJECT_STATUS" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROJECT_TASKS
--------------------------------------------------------

  CREATE TABLE "PROJECT_TASKS" 
   (	"TASK_CODE" VARCHAR2(30 BYTE), 
	"TASK_NAME" VARCHAR2(100 BYTE), 
	"TASK_START" DATE, 
	"TASK_FINISH" DATE, 
	"TASK_DESCRIPTION" VARCHAR2(500 BYTE), 
	"TASKGROUP_CODE" VARCHAR2(30 BYTE), 
	"TASK_STATUS_CODE" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROJECT_TASK_GROUPS
--------------------------------------------------------

  CREATE TABLE "PROJECT_TASK_GROUPS" 
   (	"TASKGROUP_CODE" VARCHAR2(30 BYTE), 
	"TASKGROUP_NAME" VARCHAR2(100 BYTE), 
	"TASKGROUP_DESCRIPTION" VARCHAR2(500 BYTE), 
	"PROJECT_CODE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROJECT_TASK_MANAGERS
--------------------------------------------------------

  CREATE TABLE "PROJECT_TASK_MANAGERS" 
   (	"TASK_MANAGER_CODE" VARCHAR2(30 BYTE), 
	"TASK_MANAGER_ID" VARCHAR2(50 BYTE), 
	"TASK_CODE" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROJECT_TASK_STATUS
--------------------------------------------------------

  CREATE TABLE "PROJECT_TASK_STATUS" 
   (	"TASK_STATUS_CODE" VARCHAR2(30 BYTE), 
	"TASK_STATUS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROJECT_TYPES
--------------------------------------------------------

  CREATE TABLE "PROJECT_TYPES" 
   (	"PROJECT_TYPECODE" VARCHAR2(30 BYTE), 
	"PROJECT_TYPE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TEAMS
--------------------------------------------------------

  CREATE TABLE "TEAMS" 
   (	"TEAM_CODE" NUMBER, 
	"TEAM_NAME" VARCHAR2(20 BYTE), 
	"TEAM_UPPER" VARCHAR2(20 BYTE), 
	"TEAM_SEQ" NUMBER, 
	"TEAM_USE" VARCHAR2(5 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "USERS" 
   (	"USER_ID" VARCHAR2(50 BYTE), 
	"USER_PW" VARCHAR2(50 BYTE), 
	"USER_NAME" VARCHAR2(20 BYTE), 
	"USER_EMAIL" VARCHAR2(50 BYTE), 
	"USER_PHONE" VARCHAR2(50 BYTE), 
	"USER_REGITDATE" TIMESTAMP (6), 
	"TEAM_CODE" NUMBER, 
	"POSITION_CODE" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
REM INSERTING into ACTION_FILES
SET DEFINE OFF;
REM INSERTING into APPROVAL
SET DEFINE OFF;
REM INSERTING into APPROVALDOC
SET DEFINE OFF;
REM INSERTING into APPROVALFILE
SET DEFINE OFF;
REM INSERTING into APPROVALFORM
SET DEFINE OFF;
REM INSERTING into APPROVALPATH
SET DEFINE OFF;
REM INSERTING into APPROVALREFERRER
SET DEFINE OFF;
REM INSERTING into CHATROOMS
SET DEFINE OFF;
REM INSERTING into DUTYS
SET DEFINE OFF;
Insert into DUTYS (DUTY_CODE,DUTY_NAME) values ('duty100','PMO');
Insert into DUTYS (DUTY_CODE,DUTY_NAME) values ('duty200','PM');
Insert into DUTYS (DUTY_CODE,DUTY_NAME) values ('duty300','manager');
Insert into DUTYS (DUTY_CODE,DUTY_NAME) values ('duty400','developer');
REM INSERTING into EVENTS
SET DEFINE OFF;
REM INSERTING into EVENT_GROUPS
SET DEFINE OFF;
REM INSERTING into EVENT_TYPES
SET DEFINE OFF;
REM INSERTING into MESSAGES
SET DEFINE OFF;
REM INSERTING into NOTES
SET DEFINE OFF;
REM INSERTING into PARTICIPATIONS
SET DEFINE OFF;
REM INSERTING into POSITIONS
SET DEFINE OFF;
REM INSERTING into PROJECTS
SET DEFINE OFF;
REM INSERTING into PROJECT_ISSUES
SET DEFINE OFF;
REM INSERTING into PROJECT_ISSUE_TYPES
SET DEFINE OFF;
Insert into PROJECT_ISSUE_TYPES (ISSUE_TYPE_CODE,ISSUE_TYPE) values ('issuetype100','고객변심');
Insert into PROJECT_ISSUE_TYPES (ISSUE_TYPE_CODE,ISSUE_TYPE) values ('issuetype200','일정지연');
Insert into PROJECT_ISSUE_TYPES (ISSUE_TYPE_CODE,ISSUE_TYPE) values ('issuetype300','품질개선');
Insert into PROJECT_ISSUE_TYPES (ISSUE_TYPE_CODE,ISSUE_TYPE) values ('issuetype400','기타사유');
REM INSERTING into PROJECT_MEMBERS
SET DEFINE OFF;
REM INSERTING into PROJECT_OUTPUTS
SET DEFINE OFF;
REM INSERTING into PROJECT_OUTPUT_TYPES
SET DEFINE OFF;
Insert into PROJECT_OUTPUT_TYPES (OUTPUT_TYPE_CODE,OUTPUT_TYPE) values ('R1','사용자 요구사항 정의서');
Insert into PROJECT_OUTPUT_TYPES (OUTPUT_TYPE_CODE,OUTPUT_TYPE) values ('R2','유스케이스 명세서');
Insert into PROJECT_OUTPUT_TYPES (OUTPUT_TYPE_CODE,OUTPUT_TYPE) values ('R3','요구사항 추적표');
Insert into PROJECT_OUTPUT_TYPES (OUTPUT_TYPE_CODE,OUTPUT_TYPE) values ('D1','클래스 설계서');
Insert into PROJECT_OUTPUT_TYPES (OUTPUT_TYPE_CODE,OUTPUT_TYPE) values ('D2','사용자 인터페이스 설계서');
Insert into PROJECT_OUTPUT_TYPES (OUTPUT_TYPE_CODE,OUTPUT_TYPE) values ('D3','컴포넌트 설계서');
Insert into PROJECT_OUTPUT_TYPES (OUTPUT_TYPE_CODE,OUTPUT_TYPE) values ('D4','인터페이스 설계서');
Insert into PROJECT_OUTPUT_TYPES (OUTPUT_TYPE_CODE,OUTPUT_TYPE) values ('D5','아키텍처 설계서');
Insert into PROJECT_OUTPUT_TYPES (OUTPUT_TYPE_CODE,OUTPUT_TYPE) values ('D6','총괄시험 계획서');
Insert into PROJECT_OUTPUT_TYPES (OUTPUT_TYPE_CODE,OUTPUT_TYPE) values ('D7','시스템시험 시나리오');
Insert into PROJECT_OUTPUT_TYPES (OUTPUT_TYPE_CODE,OUTPUT_TYPE) values ('D8','엔티티 관계 모형 기술서');
Insert into PROJECT_OUTPUT_TYPES (OUTPUT_TYPE_CODE,OUTPUT_TYPE) values ('D9','데이터베이스 설계서');
Insert into PROJECT_OUTPUT_TYPES (OUTPUT_TYPE_CODE,OUTPUT_TYPE) values ('D10','통합시험 시나리오');
Insert into PROJECT_OUTPUT_TYPES (OUTPUT_TYPE_CODE,OUTPUT_TYPE) values ('D11','단위시험 케이스');
Insert into PROJECT_OUTPUT_TYPES (OUTPUT_TYPE_CODE,OUTPUT_TYPE) values ('D12','데이터 전환 및 초기데이터 설계서');
Insert into PROJECT_OUTPUT_TYPES (OUTPUT_TYPE_CODE,OUTPUT_TYPE) values ('I1','프로그램 코드');
Insert into PROJECT_OUTPUT_TYPES (OUTPUT_TYPE_CODE,OUTPUT_TYPE) values ('I2','단위시험 결과서');
Insert into PROJECT_OUTPUT_TYPES (OUTPUT_TYPE_CODE,OUTPUT_TYPE) values ('I3','데이터베이스 테이블');
Insert into PROJECT_OUTPUT_TYPES (OUTPUT_TYPE_CODE,OUTPUT_TYPE) values ('T1','통합시험 결과서');
Insert into PROJECT_OUTPUT_TYPES (OUTPUT_TYPE_CODE,OUTPUT_TYPE) values ('T2','시스템시험 결과서');
Insert into PROJECT_OUTPUT_TYPES (OUTPUT_TYPE_CODE,OUTPUT_TYPE) values ('T3','사용자 지침서');
Insert into PROJECT_OUTPUT_TYPES (OUTPUT_TYPE_CODE,OUTPUT_TYPE) values ('T4','운영자 지침서');
Insert into PROJECT_OUTPUT_TYPES (OUTPUT_TYPE_CODE,OUTPUT_TYPE) values ('T5','시스템 설치 결과서');
Insert into PROJECT_OUTPUT_TYPES (OUTPUT_TYPE_CODE,OUTPUT_TYPE) values ('T6','인수시험 시나리오');
Insert into PROJECT_OUTPUT_TYPES (OUTPUT_TYPE_CODE,OUTPUT_TYPE) values ('T7','인수시험 결과서');
REM INSERTING into PROJECT_STATUS
SET DEFINE OFF;
Insert into PROJECT_STATUS (PROJECT_STATUSCODE,PROJECT_STATUS) values ('projstatus100','진행중');
Insert into PROJECT_STATUS (PROJECT_STATUSCODE,PROJECT_STATUS) values ('projstatus200','완료');
Insert into PROJECT_STATUS (PROJECT_STATUSCODE,PROJECT_STATUS) values ('projstatus300','중단');
REM INSERTING into PROJECT_TASKS
SET DEFINE OFF;
REM INSERTING into PROJECT_TASK_GROUPS
SET DEFINE OFF;
REM INSERTING into PROJECT_TASK_MANAGERS
SET DEFINE OFF;
REM INSERTING into PROJECT_TASK_STATUS
SET DEFINE OFF;
Insert into PROJECT_TASK_STATUS (TASK_STATUS_CODE,TASK_STATUS) values ('taskstatus100','진행중');
Insert into PROJECT_TASK_STATUS (TASK_STATUS_CODE,TASK_STATUS) values ('taskstatus200','완료');
Insert into PROJECT_TASK_STATUS (TASK_STATUS_CODE,TASK_STATUS) values ('taskstatus300','대기');
REM INSERTING into PROJECT_TYPES
SET DEFINE OFF;
Insert into PROJECT_TYPES (PROJECT_TYPECODE,PROJECT_TYPE) values ('devtype100','연구');
Insert into PROJECT_TYPES (PROJECT_TYPECODE,PROJECT_TYPE) values ('devtype200','개발');
Insert into PROJECT_TYPES (PROJECT_TYPECODE,PROJECT_TYPE) values ('devtype300','디자인');
Insert into PROJECT_TYPES (PROJECT_TYPECODE,PROJECT_TYPE) values ('devtype400','품질');
Insert into PROJECT_TYPES (PROJECT_TYPECODE,PROJECT_TYPE) values ('devtype500','유지보수');
REM INSERTING into TEAMS
SET DEFINE OFF;
REM INSERTING into USERS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PK_ACTION_FILES
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_ACTION_FILES" ON "ACTION_FILES" ("ACTIONFILE_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_APPROVAL
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_APPROVAL" ON "APPROVAL" ("AP_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_APPROVALDOC
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_APPROVALDOC" ON "APPROVALDOC" ("AP_DOC_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_APPROVALFILE
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_APPROVALFILE" ON "APPROVALFILE" ("AP_FILE_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_APPROVALFORM
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_APPROVALFORM" ON "APPROVALFORM" ("AP_FORM_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_APPROVALPATH
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_APPROVALPATH" ON "APPROVALPATH" ("AP_PATH_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_APPROVALREFERRER
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_APPROVALREFERRER" ON "APPROVALREFERRER" ("AP_DOC_NO", "AP_REFERRER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_CHATROOMS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_CHATROOMS" ON "CHATROOMS" ("CONVERSATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_DUTYS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_DUTYS" ON "DUTYS" ("DUTY_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_EVENTS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_EVENTS" ON "EVENTS" ("EVENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_EVENT_GROUPS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_EVENT_GROUPS" ON "EVENT_GROUPS" ("EVENT_ID", "USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_EVENT_TYPES
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_EVENT_TYPES" ON "EVENT_TYPES" ("EVENT_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_MESSAGES
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_MESSAGES" ON "MESSAGES" ("MESSAGE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_NOTES
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_NOTES" ON "NOTES" ("NOTE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PARTICIPATIONS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_PARTICIPATIONS" ON "PARTICIPATIONS" ("USER_ID", "CONVERSATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_POSITIONS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_POSITIONS" ON "POSITIONS" ("POSITION_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PROJECTS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_PROJECTS" ON "PROJECTS" ("PROJECT_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PROJECT_ISSUES
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_PROJECT_ISSUES" ON "PROJECT_ISSUES" ("ISSUE_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PROJECT_ISSUE_TYPES
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_PROJECT_ISSUE_TYPES" ON "PROJECT_ISSUE_TYPES" ("ISSUE_TYPE_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PROJECT_MEMBERS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_PROJECT_MEMBERS" ON "PROJECT_MEMBERS" ("PROJECT_JOINCODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PROJECT_OUTPUTS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_PROJECT_OUTPUTS" ON "PROJECT_OUTPUTS" ("OUTPUT_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PROJECT_OUTPUT_TYPES
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_PROJECT_OUTPUT_TYPES" ON "PROJECT_OUTPUT_TYPES" ("OUTPUT_TYPE_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PROJECT_STATUS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_PROJECT_STATUS" ON "PROJECT_STATUS" ("PROJECT_STATUSCODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PROJECT_TASKS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_PROJECT_TASKS" ON "PROJECT_TASKS" ("TASK_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PROJECT_TASK_GROUPS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_PROJECT_TASK_GROUPS" ON "PROJECT_TASK_GROUPS" ("TASKGROUP_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PROJECT_TASK_MANAGERS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_PROJECT_TASK_MANAGERS" ON "PROJECT_TASK_MANAGERS" ("TASK_MANAGER_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PROJECT_TASK_STATUS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_PROJECT_TASK_STATUS" ON "PROJECT_TASK_STATUS" ("TASK_STATUS_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PROJECT_TYPES
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_PROJECT_TYPES" ON "PROJECT_TYPES" ("PROJECT_TYPECODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TEAMS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_TEAMS" ON "TEAMS" ("TEAM_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_USERS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_USERS" ON "USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ACTION_FILES
--------------------------------------------------------

  ALTER TABLE "ACTION_FILES" ADD CONSTRAINT "PK_ACTION_FILES" PRIMARY KEY ("ACTIONFILE_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ACTION_FILES" MODIFY ("ACTIONFILE_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "ACTION_FILES" MODIFY ("ACTIONFILE_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "ACTION_FILES" MODIFY ("ACTIONFILE_PATH" NOT NULL ENABLE);
 
  ALTER TABLE "ACTION_FILES" MODIFY ("ISSUE_CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table APPROVAL
--------------------------------------------------------

  ALTER TABLE "APPROVAL" ADD CONSTRAINT "PK_APPROVAL" PRIMARY KEY ("AP_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "APPROVAL" MODIFY ("AP_NO" NOT NULL ENABLE);
 
  ALTER TABLE "APPROVAL" MODIFY ("AP_DOC_NO" NOT NULL ENABLE);
 
  ALTER TABLE "APPROVAL" MODIFY ("AP_APPROVER" NOT NULL ENABLE);
 
  ALTER TABLE "APPROVAL" MODIFY ("AP_DUTY_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "APPROVAL" MODIFY ("AP_STEP" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table APPROVALDOC
--------------------------------------------------------

  ALTER TABLE "APPROVALDOC" ADD CONSTRAINT "PK_APPROVALDOC" PRIMARY KEY ("AP_DOC_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "APPROVALDOC" MODIFY ("AP_DOC_NO" NOT NULL ENABLE);
 
  ALTER TABLE "APPROVALDOC" MODIFY ("AP_FORM_NO" NOT NULL ENABLE);
 
  ALTER TABLE "APPROVALDOC" MODIFY ("AP_DOC_WRITER" NOT NULL ENABLE);
 
  ALTER TABLE "APPROVALDOC" MODIFY ("AP_DOC_TITLE" NOT NULL ENABLE);
 
  ALTER TABLE "APPROVALDOC" MODIFY ("AP_DOC_CONTENT" NOT NULL ENABLE);
 
  ALTER TABLE "APPROVALDOC" MODIFY ("AP_DOC_STATUS" NOT NULL ENABLE);
 
  ALTER TABLE "APPROVALDOC" MODIFY ("AP_DOC_STEP" NOT NULL ENABLE);
 
  ALTER TABLE "APPROVALDOC" MODIFY ("AP_DOC_CREATEDATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table APPROVALFILE
--------------------------------------------------------

  ALTER TABLE "APPROVALFILE" ADD CONSTRAINT "PK_APPROVALFILE" PRIMARY KEY ("AP_FILE_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "APPROVALFILE" MODIFY ("AP_FILE_NO" NOT NULL ENABLE);
 
  ALTER TABLE "APPROVALFILE" MODIFY ("AP_DOC_NO" NOT NULL ENABLE);
 
  ALTER TABLE "APPROVALFILE" MODIFY ("AP_FILE_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "APPROVALFILE" MODIFY ("AP_FILE_PATH" NOT NULL ENABLE);
 
  ALTER TABLE "APPROVALFILE" MODIFY ("AP_FILE_TYPE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table APPROVALFORM
--------------------------------------------------------

  ALTER TABLE "APPROVALFORM" ADD CONSTRAINT "PK_APPROVALFORM" PRIMARY KEY ("AP_FORM_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "APPROVALFORM" MODIFY ("AP_FORM_NO" NOT NULL ENABLE);
 
  ALTER TABLE "APPROVALFORM" MODIFY ("AP_PATH_NO" NOT NULL ENABLE);
 
  ALTER TABLE "APPROVALFORM" MODIFY ("AP_FORM_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "APPROVALFORM" MODIFY ("AP_FORM_CONTENT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table APPROVALPATH
--------------------------------------------------------

  ALTER TABLE "APPROVALPATH" ADD CONSTRAINT "PK_APPROVALPATH" PRIMARY KEY ("AP_PATH_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "APPROVALPATH" MODIFY ("AP_PATH_NO" NOT NULL ENABLE);
 
  ALTER TABLE "APPROVALPATH" MODIFY ("AP_PATH1" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table APPROVALREFERRER
--------------------------------------------------------

  ALTER TABLE "APPROVALREFERRER" ADD CONSTRAINT "PK_APPROVALREFERRER" PRIMARY KEY ("AP_DOC_NO", "AP_REFERRER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "APPROVALREFERRER" MODIFY ("AP_DOC_NO" NOT NULL ENABLE);
 
  ALTER TABLE "APPROVALREFERRER" MODIFY ("AP_REFERRER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CHATROOMS
--------------------------------------------------------

  ALTER TABLE "CHATROOMS" ADD CONSTRAINT "PK_CHATROOMS" PRIMARY KEY ("CONVERSATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "CHATROOMS" MODIFY ("CONVERSATION_ID" NOT NULL ENABLE);
 
  ALTER TABLE "CHATROOMS" MODIFY ("LAST_MESSAGE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "CHATROOMS" MODIFY ("CONVERSATION_CREATION_TIME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DUTYS
--------------------------------------------------------

  ALTER TABLE "DUTYS" ADD CONSTRAINT "PK_DUTYS" PRIMARY KEY ("DUTY_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "DUTYS" MODIFY ("DUTY_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "DUTYS" MODIFY ("DUTY_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EVENTS
--------------------------------------------------------

  ALTER TABLE "EVENTS" ADD CONSTRAINT "PK_EVENTS" PRIMARY KEY ("EVENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "EVENTS" MODIFY ("EVENT_ID" NOT NULL ENABLE);
 
  ALTER TABLE "EVENTS" MODIFY ("EVENT_TITLE" NOT NULL ENABLE);
 
  ALTER TABLE "EVENTS" MODIFY ("EVENT_START_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "EVENTS" MODIFY ("EVENT_FINISH_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "EVENTS" MODIFY ("EVENT_TYPE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EVENT_GROUPS
--------------------------------------------------------

  ALTER TABLE "EVENT_GROUPS" ADD CONSTRAINT "PK_EVENT_GROUPS" PRIMARY KEY ("EVENT_ID", "USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "EVENT_GROUPS" MODIFY ("EVENT_ID" NOT NULL ENABLE);
 
  ALTER TABLE "EVENT_GROUPS" MODIFY ("USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EVENT_TYPES
--------------------------------------------------------

  ALTER TABLE "EVENT_TYPES" ADD CONSTRAINT "PK_EVENT_TYPES" PRIMARY KEY ("EVENT_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "EVENT_TYPES" MODIFY ("EVENT_TYPE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "EVENT_TYPES" MODIFY ("EVENT_TYPE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MESSAGES
--------------------------------------------------------

  ALTER TABLE "MESSAGES" ADD CONSTRAINT "PK_MESSAGES" PRIMARY KEY ("MESSAGE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "MESSAGES" MODIFY ("MESSAGE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "MESSAGES" MODIFY ("AUTHOR_ID" NOT NULL ENABLE);
 
  ALTER TABLE "MESSAGES" MODIFY ("CONVERSATION_ID" NOT NULL ENABLE);
 
  ALTER TABLE "MESSAGES" MODIFY ("CONTENT" NOT NULL ENABLE);
 
  ALTER TABLE "MESSAGES" MODIFY ("CREATION_TIME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NOTES
--------------------------------------------------------

  ALTER TABLE "NOTES" ADD CONSTRAINT "PK_NOTES" PRIMARY KEY ("NOTE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "NOTES" MODIFY ("NOTE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "NOTES" MODIFY ("AUTHOR_ID" NOT NULL ENABLE);
 
  ALTER TABLE "NOTES" MODIFY ("RECEIVER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "NOTES" MODIFY ("CONTENT" NOT NULL ENABLE);
 
  ALTER TABLE "NOTES" MODIFY ("CREATION_TIME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PARTICIPATIONS
--------------------------------------------------------

  ALTER TABLE "PARTICIPATIONS" ADD CONSTRAINT "PK_PARTICIPATIONS" PRIMARY KEY ("USER_ID", "CONVERSATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PARTICIPATIONS" MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "PARTICIPATIONS" MODIFY ("CONVERSATION_ID" NOT NULL ENABLE);
 
  ALTER TABLE "PARTICIPATIONS" MODIFY ("JOIN_TIME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table POSITIONS
--------------------------------------------------------

  ALTER TABLE "POSITIONS" ADD CONSTRAINT "PK_POSITIONS" PRIMARY KEY ("POSITION_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "POSITIONS" MODIFY ("POSITION_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "POSITIONS" MODIFY ("POSITION_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROJECTS
--------------------------------------------------------

  ALTER TABLE "PROJECTS" ADD CONSTRAINT "PK_PROJECTS" PRIMARY KEY ("PROJECT_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PROJECTS" MODIFY ("PROJECT_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "PROJECTS" MODIFY ("PROJECT_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "PROJECTS" MODIFY ("PROJECT_SUBNAME" NOT NULL ENABLE);
 
  ALTER TABLE "PROJECTS" MODIFY ("PROJECT_START" NOT NULL ENABLE);
 
  ALTER TABLE "PROJECTS" MODIFY ("PROJECT_FINISH" NOT NULL ENABLE);
 
  ALTER TABLE "PROJECTS" MODIFY ("PROJECT_PM" NOT NULL ENABLE);
 
  ALTER TABLE "PROJECTS" MODIFY ("PROJECT_TYPECODE" NOT NULL ENABLE);
 
  ALTER TABLE "PROJECTS" MODIFY ("PROJECT_STATUSCODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROJECT_ISSUES
--------------------------------------------------------

  ALTER TABLE "PROJECT_ISSUES" ADD CONSTRAINT "PK_PROJECT_ISSUES" PRIMARY KEY ("ISSUE_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PROJECT_ISSUES" MODIFY ("ISSUE_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "PROJECT_ISSUES" MODIFY ("ISSUE_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "PROJECT_ISSUES" MODIFY ("ISSUE_USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "PROJECT_ISSUES" MODIFY ("ISSUE_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "PROJECT_ISSUES" MODIFY ("ISSUE_ACTION_ID" NOT NULL ENABLE);
 
  ALTER TABLE "PROJECT_ISSUES" MODIFY ("ISSUE_ACTION_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "PROJECT_ISSUES" MODIFY ("ISSUE_TYPE_CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROJECT_ISSUE_TYPES
--------------------------------------------------------

  ALTER TABLE "PROJECT_ISSUE_TYPES" ADD CONSTRAINT "PK_PROJECT_ISSUE_TYPES" PRIMARY KEY ("ISSUE_TYPE_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PROJECT_ISSUE_TYPES" MODIFY ("ISSUE_TYPE_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "PROJECT_ISSUE_TYPES" MODIFY ("ISSUE_TYPE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROJECT_MEMBERS
--------------------------------------------------------

  ALTER TABLE "PROJECT_MEMBERS" ADD CONSTRAINT "PK_PROJECT_MEMBERS" PRIMARY KEY ("PROJECT_JOINCODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PROJECT_MEMBERS" MODIFY ("PROJECT_JOINCODE" NOT NULL ENABLE);
 
  ALTER TABLE "PROJECT_MEMBERS" MODIFY ("PROJECT_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "PROJECT_MEMBERS" MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "PROJECT_MEMBERS" MODIFY ("DUTY_CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROJECT_OUTPUTS
--------------------------------------------------------

  ALTER TABLE "PROJECT_OUTPUTS" ADD CONSTRAINT "PK_PROJECT_OUTPUTS" PRIMARY KEY ("OUTPUT_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PROJECT_OUTPUTS" MODIFY ("OUTPUT_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "PROJECT_OUTPUTS" MODIFY ("OUTPUT_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "PROJECT_OUTPUTS" MODIFY ("OUTPUT_USER" NOT NULL ENABLE);
 
  ALTER TABLE "PROJECT_OUTPUTS" MODIFY ("OUTPUT_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "PROJECT_OUTPUTS" MODIFY ("OUTPUT_PATH" NOT NULL ENABLE);
 
  ALTER TABLE "PROJECT_OUTPUTS" MODIFY ("OUTPUT_TYPE_CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROJECT_OUTPUT_TYPES
--------------------------------------------------------

  ALTER TABLE "PROJECT_OUTPUT_TYPES" ADD CONSTRAINT "PK_PROJECT_OUTPUT_TYPES" PRIMARY KEY ("OUTPUT_TYPE_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PROJECT_OUTPUT_TYPES" MODIFY ("OUTPUT_TYPE_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "PROJECT_OUTPUT_TYPES" MODIFY ("OUTPUT_TYPE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROJECT_STATUS
--------------------------------------------------------

  ALTER TABLE "PROJECT_STATUS" ADD CONSTRAINT "PK_PROJECT_STATUS" PRIMARY KEY ("PROJECT_STATUSCODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PROJECT_STATUS" MODIFY ("PROJECT_STATUSCODE" NOT NULL ENABLE);
 
  ALTER TABLE "PROJECT_STATUS" MODIFY ("PROJECT_STATUS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROJECT_TASKS
--------------------------------------------------------

  ALTER TABLE "PROJECT_TASKS" ADD CONSTRAINT "PK_PROJECT_TASKS" PRIMARY KEY ("TASK_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PROJECT_TASKS" MODIFY ("TASK_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "PROJECT_TASKS" MODIFY ("TASK_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "PROJECT_TASKS" MODIFY ("TASK_START" NOT NULL ENABLE);
 
  ALTER TABLE "PROJECT_TASKS" MODIFY ("TASK_FINISH" NOT NULL ENABLE);
 
  ALTER TABLE "PROJECT_TASKS" MODIFY ("TASKGROUP_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "PROJECT_TASKS" MODIFY ("TASK_STATUS_CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROJECT_TASK_GROUPS
--------------------------------------------------------

  ALTER TABLE "PROJECT_TASK_GROUPS" ADD CONSTRAINT "PK_PROJECT_TASK_GROUPS" PRIMARY KEY ("TASKGROUP_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PROJECT_TASK_GROUPS" MODIFY ("TASKGROUP_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "PROJECT_TASK_GROUPS" MODIFY ("TASKGROUP_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "PROJECT_TASK_GROUPS" MODIFY ("TASKGROUP_DESCRIPTION" NOT NULL ENABLE);
 
  ALTER TABLE "PROJECT_TASK_GROUPS" MODIFY ("PROJECT_CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROJECT_TASK_MANAGERS
--------------------------------------------------------

  ALTER TABLE "PROJECT_TASK_MANAGERS" ADD CONSTRAINT "PK_PROJECT_TASK_MANAGERS" PRIMARY KEY ("TASK_MANAGER_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PROJECT_TASK_MANAGERS" MODIFY ("TASK_MANAGER_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "PROJECT_TASK_MANAGERS" MODIFY ("TASK_MANAGER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "PROJECT_TASK_MANAGERS" MODIFY ("TASK_CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROJECT_TASK_STATUS
--------------------------------------------------------

  ALTER TABLE "PROJECT_TASK_STATUS" ADD CONSTRAINT "PK_PROJECT_TASK_STATUS" PRIMARY KEY ("TASK_STATUS_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PROJECT_TASK_STATUS" MODIFY ("TASK_STATUS_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "PROJECT_TASK_STATUS" MODIFY ("TASK_STATUS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROJECT_TYPES
--------------------------------------------------------

  ALTER TABLE "PROJECT_TYPES" ADD CONSTRAINT "PK_PROJECT_TYPES" PRIMARY KEY ("PROJECT_TYPECODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PROJECT_TYPES" MODIFY ("PROJECT_TYPECODE" NOT NULL ENABLE);
 
  ALTER TABLE "PROJECT_TYPES" MODIFY ("PROJECT_TYPE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TEAMS
--------------------------------------------------------

  ALTER TABLE "TEAMS" ADD CONSTRAINT "PK_TEAMS" PRIMARY KEY ("TEAM_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "TEAMS" MODIFY ("TEAM_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "TEAMS" MODIFY ("TEAM_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "TEAMS" MODIFY ("TEAM_USE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "USERS" ADD CONSTRAINT "PK_USERS" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "USERS" MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "USERS" MODIFY ("USER_PW" NOT NULL ENABLE);
 
  ALTER TABLE "USERS" MODIFY ("USER_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "USERS" MODIFY ("USER_EMAIL" NOT NULL ENABLE);
 
  ALTER TABLE "USERS" MODIFY ("USER_PHONE" NOT NULL ENABLE);
 
  ALTER TABLE "USERS" MODIFY ("TEAM_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "USERS" MODIFY ("POSITION_CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ACTION_FILES
--------------------------------------------------------

  ALTER TABLE "ACTION_FILES" ADD CONSTRAINT "FK_ISSUES_TO_ACTION_FILES" FOREIGN KEY ("ISSUE_CODE")
	  REFERENCES "PROJECT_ISSUES" ("ISSUE_CODE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table APPROVAL
--------------------------------------------------------

  ALTER TABLE "APPROVAL" ADD CONSTRAINT "FK_APPROVALDOC_TO_APPROVAL" FOREIGN KEY ("AP_DOC_NO")
	  REFERENCES "APPROVALDOC" ("AP_DOC_NO") ENABLE;
 
  ALTER TABLE "APPROVAL" ADD CONSTRAINT "FK_USERS_TO_APPROVAL" FOREIGN KEY ("AP_APPROVER")
	  REFERENCES "USERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table APPROVALDOC
--------------------------------------------------------

  ALTER TABLE "APPROVALDOC" ADD CONSTRAINT "FK_APPROVALFORM_TO_APPROVALDOC" FOREIGN KEY ("AP_FORM_NO")
	  REFERENCES "APPROVALFORM" ("AP_FORM_NO") ENABLE;
 
  ALTER TABLE "APPROVALDOC" ADD CONSTRAINT "FK_USERS_TO_APPROVALDOC" FOREIGN KEY ("AP_DOC_WRITER")
	  REFERENCES "USERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table APPROVALFILE
--------------------------------------------------------

  ALTER TABLE "APPROVALFILE" ADD CONSTRAINT "FK_APPROVALDOC_TO_APPROVALFILE" FOREIGN KEY ("AP_DOC_NO")
	  REFERENCES "APPROVALDOC" ("AP_DOC_NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table APPROVALFORM
--------------------------------------------------------

  ALTER TABLE "APPROVALFORM" ADD CONSTRAINT "FK_APPROVALPATH_TO_APRVLFRM" FOREIGN KEY ("AP_PATH_NO")
	  REFERENCES "APPROVALPATH" ("AP_PATH_NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table APPROVALREFERRER
--------------------------------------------------------

  ALTER TABLE "APPROVALREFERRER" ADD CONSTRAINT "FK_APPROVALDOC_TO_APRVLRFR" FOREIGN KEY ("AP_DOC_NO")
	  REFERENCES "APPROVALDOC" ("AP_DOC_NO") ENABLE;
 
  ALTER TABLE "APPROVALREFERRER" ADD CONSTRAINT "FK_USERS_TO_APPROVALREFERRER" FOREIGN KEY ("AP_REFERRER")
	  REFERENCES "USERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EVENTS
--------------------------------------------------------

  ALTER TABLE "EVENTS" ADD CONSTRAINT "FK_EVENT_TYPES_TO_EVENTS" FOREIGN KEY ("EVENT_TYPE_ID")
	  REFERENCES "EVENT_TYPES" ("EVENT_TYPE_ID") ENABLE;
 
  ALTER TABLE "EVENTS" ADD CONSTRAINT "FK_PROJECTS_TO_EVENTS" FOREIGN KEY ("PROJECT_CODE")
	  REFERENCES "PROJECTS" ("PROJECT_CODE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EVENT_GROUPS
--------------------------------------------------------

  ALTER TABLE "EVENT_GROUPS" ADD CONSTRAINT "FK_EVENTS_TO_EVENT_GROUPS" FOREIGN KEY ("EVENT_ID")
	  REFERENCES "EVENTS" ("EVENT_ID") ENABLE;
 
  ALTER TABLE "EVENT_GROUPS" ADD CONSTRAINT "FK_USERS_TO_EVENT_GROUPS" FOREIGN KEY ("USER_ID")
	  REFERENCES "USERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MESSAGES
--------------------------------------------------------

  ALTER TABLE "MESSAGES" ADD CONSTRAINT "FK_CHATROOMS_TO_MESSAGES" FOREIGN KEY ("CONVERSATION_ID")
	  REFERENCES "CHATROOMS" ("CONVERSATION_ID") ENABLE;
 
  ALTER TABLE "MESSAGES" ADD CONSTRAINT "FK_USERS_TO_MESSAGES" FOREIGN KEY ("AUTHOR_ID")
	  REFERENCES "USERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NOTES
--------------------------------------------------------

  ALTER TABLE "NOTES" ADD CONSTRAINT "FK_USERS_TO_NOTES" FOREIGN KEY ("RECEIVER_ID")
	  REFERENCES "USERS" ("USER_ID") ENABLE;
 
  ALTER TABLE "NOTES" ADD CONSTRAINT "FK_USERS_TO_NOTES2" FOREIGN KEY ("AUTHOR_ID")
	  REFERENCES "USERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PARTICIPATIONS
--------------------------------------------------------

  ALTER TABLE "PARTICIPATIONS" ADD CONSTRAINT "FK_CHATROOMS_TO_PARTICIPATIONS" FOREIGN KEY ("CONVERSATION_ID")
	  REFERENCES "CHATROOMS" ("CONVERSATION_ID") ENABLE;
 
  ALTER TABLE "PARTICIPATIONS" ADD CONSTRAINT "FK_USERS_TO_PARTICIPATIONS" FOREIGN KEY ("USER_ID")
	  REFERENCES "USERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROJECTS
--------------------------------------------------------

  ALTER TABLE "PROJECTS" ADD CONSTRAINT "FK_PROJECT_STATUS_TO_PROJECTS" FOREIGN KEY ("PROJECT_STATUSCODE")
	  REFERENCES "PROJECT_STATUS" ("PROJECT_STATUSCODE") ENABLE;
 
  ALTER TABLE "PROJECTS" ADD CONSTRAINT "FK_PROJECT_TYPES_TO_PROJECTS" FOREIGN KEY ("PROJECT_TYPECODE")
	  REFERENCES "PROJECT_TYPES" ("PROJECT_TYPECODE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROJECT_ISSUES
--------------------------------------------------------

  ALTER TABLE "PROJECT_ISSUES" ADD CONSTRAINT "FK_PRJCT_IS_TPS_TO_PRJCT_IS" FOREIGN KEY ("ISSUE_TYPE_CODE")
	  REFERENCES "PROJECT_ISSUE_TYPES" ("ISSUE_TYPE_CODE") ENABLE;
 
  ALTER TABLE "PROJECT_ISSUES" ADD CONSTRAINT "FK_PRJCT_TASKS_TO_PRJCT_IS" FOREIGN KEY ("TASK_CODE")
	  REFERENCES "PROJECT_TASKS" ("TASK_CODE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROJECT_MEMBERS
--------------------------------------------------------

  ALTER TABLE "PROJECT_MEMBERS" ADD CONSTRAINT "FK_DUTYS_TO_PROJECT_MEMBERS" FOREIGN KEY ("DUTY_CODE")
	  REFERENCES "DUTYS" ("DUTY_CODE") ENABLE;
 
  ALTER TABLE "PROJECT_MEMBERS" ADD CONSTRAINT "FK_PROJECTS_TO_PROJECT_MEMBERS" FOREIGN KEY ("PROJECT_CODE")
	  REFERENCES "PROJECTS" ("PROJECT_CODE") ENABLE;
 
  ALTER TABLE "PROJECT_MEMBERS" ADD CONSTRAINT "FK_USERS_TO_PROJECT_MEMBERS" FOREIGN KEY ("USER_ID")
	  REFERENCES "USERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROJECT_OUTPUTS
--------------------------------------------------------

  ALTER TABLE "PROJECT_OUTPUTS" ADD CONSTRAINT "FK_TASKS_TO_PROJECT_OUTPUTS" FOREIGN KEY ("TASK_CODE")
	  REFERENCES "PROJECT_TASKS" ("TASK_CODE") ENABLE;
 
  ALTER TABLE "PROJECT_OUTPUTS" ADD CONSTRAINT "FK_TPS_TO_PRJCT_OTPTS" FOREIGN KEY ("OUTPUT_TYPE_CODE")
	  REFERENCES "PROJECT_OUTPUT_TYPES" ("OUTPUT_TYPE_CODE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROJECT_TASKS
--------------------------------------------------------

  ALTER TABLE "PROJECT_TASKS" ADD CONSTRAINT "FK_GRPS_TO_PRJCT_TSKS" FOREIGN KEY ("TASKGROUP_CODE")
	  REFERENCES "PROJECT_TASK_GROUPS" ("TASKGROUP_CODE") ENABLE;
 
  ALTER TABLE "PROJECT_TASKS" ADD CONSTRAINT "FK_PRJCT_STS_TO_PRJCT_TSKS" FOREIGN KEY ("TASK_STATUS_CODE")
	  REFERENCES "PROJECT_TASK_STATUS" ("TASK_STATUS_CODE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROJECT_TASK_GROUPS
--------------------------------------------------------

  ALTER TABLE "PROJECT_TASK_GROUPS" ADD CONSTRAINT "FK_PRJCTS_TO_PRJCT_TSK_GRPS" FOREIGN KEY ("PROJECT_CODE")
	  REFERENCES "PROJECTS" ("PROJECT_CODE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROJECT_TASK_MANAGERS
--------------------------------------------------------

  ALTER TABLE "PROJECT_TASK_MANAGERS" ADD CONSTRAINT "FK_TSKS_TO_PRJCT_MNGRS" FOREIGN KEY ("TASK_CODE")
	  REFERENCES "PROJECT_TASKS" ("TASK_CODE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "USERS" ADD CONSTRAINT "FK_POSITIONS_TO_USERS" FOREIGN KEY ("POSITION_CODE")
	  REFERENCES "POSITIONS" ("POSITION_CODE") ENABLE;
 
  ALTER TABLE "USERS" ADD CONSTRAINT "FK_TEAMS_TO_USERS" FOREIGN KEY ("TEAM_CODE")
	  REFERENCES "TEAMS" ("TEAM_CODE") ENABLE;
